version: '3.8'

services:
  # PostgreSQL Database (same as production)
  postgres:
    image: postgres:15-alpine
    container_name: vsl-alchemist-postgres-dev
    environment:
      POSTGRES_DB: vsl_alchemist
      POSTGRES_USER: vsl_user
      POSTGRES_PASSWORD: vsl_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vsl_user -d vsl_alchemist"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # VSL-Alchemist Application (Development)
  app:
    build:
      context: .
      target: builder
    container_name: vsl-alchemist-app-dev
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://vsl_user:vsl_password@postgres:5432/vsl_alchemist
      - JWT_SECRET=dev_jwt_secret_here
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - PORT=3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    command: npm run dev
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data_dev: 