services:
  - type: web
    name: vsl-alchemist
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: vsl-alchemist-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: vsl-alchemist-db
    databaseName: vsl_alchemist
    user: vsl_user
    plan: starter 