services:
  - type: web
    name: vsl-alchemist
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    dockerContext: .
    dockerCommand: docker-compose -f render-docker-compose.yml up --build -d
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: POSTGRES_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    healthCheckPath: /health
    autoDeploy: true

databases:
  - name: vsl-alchemist-db
    databaseName: vsl_alchemist
    user: vsl_user
    plan: starter 